/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modena.ui.appFrames.forms.newUserForms;

import com.toedter.calendar.JDateChooser;
import java.awt.FlowLayout;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTextField;
import resources.dataArray.JobsAvailable;
import resources.dataArray.NRList;

/**
 *
 * @author felip
 */
public class NewUserFormsFrame extends javax.swing.JFrame {

    /**
     * Creates new form newUserForms
     */
    public NewUserFormsFrame() {
        initComponents();
        initCustomComponents();
        newDependentTextFieldList = new ArrayList<>();
        JobLocalInputListOptionsPopulate();
    }

    public class NewDependentInput {

        JTextField name;
        JTextField dependency;
        JTextField age;

        NewDependentInput(JTextField name, JTextField dependency, JTextField age) {
            this.name = name;
            this.dependency = dependency;
            this.age = age;
        }

        @Override
        public String toString() {
            return "Name: " + name.getText() + ", Dependency: " + dependency.getText() + ", Age: " + age.getText();
        }

    }

    public class NRChosenInput {

        JDateChooser date;
        String nr;

        NRChosenInput(JDateChooser date, String nr) {
            this.date = date;
            this.nr = nr;
        }

        @Override
        public String toString() {
            return "Nr: " + nr + " / " + "Date: " + date.getDate();
        }

    }

    private void initCustomComponents() {
        dependentsListPanel.setLayout(new BoxLayout(dependentsListPanel, BoxLayout.Y_AXIS));
        jobOperationNRsListSelectedjPanel.setLayout(new BoxLayout(jobOperationNRsListSelectedjPanel, BoxLayout.Y_AXIS));

        jobOperationNRListPopulate();
        jobFunctionjListPopulate();
    }

    private void jobOperationNRListPopulate() {
        jobOperationNRsList.setModel(new javax.swing.AbstractListModel<String>() {
            NRList nrList = new NRList();
            String[] strings = nrList.NRListConcat();

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        jobOperationNRsjscrollPane.setViewportView(jobOperationNRsList);

    }

    private void jobFunctionjListPopulate() {
        jobFunctionjList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = jobList.listOfJobsTitle();

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        jobFunctionjListjScrollPane.setViewportView(jobFunctionjList);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();
        cpfJlabel = new javax.swing.JLabel();
        rgjLabel = new javax.swing.JLabel();
        workPermitjLabel = new javax.swing.JLabel();
        pisjLabel = new javax.swing.JLabel();
        militaryjLabel = new javax.swing.JLabel();
        namejTextField = new javax.swing.JTextField();
        rgjTextField = new javax.swing.JTextField();
        cpfjTextField = new javax.swing.JTextField();
        workPermitjTextField = new javax.swing.JTextField();
        militaryjTextField = new javax.swing.JTextField();
        pisjTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        streetjTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        adressComplementjLabel = new javax.swing.JLabel();
        adressComplementjTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        neighborhoodjTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cityjTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cepjTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        hieringDatejDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        asoDatejDateChooser = new com.toedter.calendar.JDateChooser();
        jobFunctionjListjScrollPane = new javax.swing.JScrollPane();
        jobFunctionjList = new javax.swing.JList<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        salaryjTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jobLocalInputList = new javax.swing.JList<>();
        addNewDependentButton = new javax.swing.JButton();
        dependentsListScrollPane = new javax.swing.JScrollPane();
        dependentsListPanel = new javax.swing.JPanel();
        saveFormsjButton = new javax.swing.JButton();
        jobOperationNRListjPanel = new javax.swing.JPanel();
        jobOperationNRsjscrollPane = new javax.swing.JScrollPane();
        jobOperationNRsList = new javax.swing.JList<>();
        jobOpeationNRsListSelectedjScrollPane = new javax.swing.JScrollPane();
        jobOperationNRsListSelectedjPanel = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Adicionar novo colaborador");

        nameJLabel.setLabelFor(namejTextField);
        nameJLabel.setText("Nome do colaborador");

        cpfJlabel.setLabelFor(cpfjTextField);
        cpfJlabel.setText("CPF");

        rgjLabel.setLabelFor(rgjLabel);
        rgjLabel.setText("RG");

        workPermitjLabel.setLabelFor(workPermitjTextField);
        workPermitjLabel.setText("Carteira de trabalho");

        pisjLabel.setText("PIS");

        militaryjLabel.setText("Reservista");

        namejTextField.setText("user1");

        rgjTextField.setText("502332578");

        cpfjTextField.setText("46260974809");

        workPermitjTextField.setText("numero carteira");

        militaryjTextField.setText("militara valor");

        pisjTextField.setText("PIS value");

        jLabel9.setText("Rua");

        streetjTextField.setText("rua tal");

        jLabel8.setText("Possui dependentes?");

        adressComplementjLabel.setText("Complemento");

        adressComplementjTextField.setText("complemento tal");

        jLabel11.setText("Bairro");

        neighborhoodjTextField.setText("bairro tal");

        jLabel12.setText("Cidade");

        cityjTextField.setText("ciadede tal");

        jLabel13.setText("CEP");

        cepjTextField.setText("0642900");

        jLabel14.setText("Data de contratação");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Endereço");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Registro de contratação");

        jLabel16.setText("Data  de ASO (exame médico)");

        jobFunctionjList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "lista de funções de JobsAvailabe.java" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jobFunctionjList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jobFunctionjListMouseClicked(evt);
            }
        });
        jobFunctionjListjScrollPane.setViewportView(jobFunctionjList);

        jLabel17.setText("Função");

        jLabel18.setText("Salário ( usar ponto (.) para centavos)");

        salaryjTextField.setText("1500");

        jLabel19.setText("Local de operação");

        jobLocalInputList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jobLocalInputListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jobLocalInputList);

        addNewDependentButton.setText("Adicionar dependente");
        addNewDependentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addNewDependentButtonMouseClicked(evt);
            }
        });

        dependentsListPanel.setFocusCycleRoot(true);

        javax.swing.GroupLayout dependentsListPanelLayout = new javax.swing.GroupLayout(dependentsListPanel);
        dependentsListPanel.setLayout(dependentsListPanelLayout);
        dependentsListPanelLayout.setHorizontalGroup(
            dependentsListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 878, Short.MAX_VALUE)
        );
        dependentsListPanelLayout.setVerticalGroup(
            dependentsListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );

        dependentsListScrollPane.setViewportView(dependentsListPanel);

        saveFormsjButton.setText("Salvar");
        saveFormsjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveFormsjButtonMouseClicked(evt);
            }
        });

        jobOperationNRsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "lista de nrs de NRList.java" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jobOperationNRsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jobOperationNRsListMouseReleased(evt);
            }
        });
        jobOperationNRsjscrollPane.setViewportView(jobOperationNRsList);

        javax.swing.GroupLayout jobOperationNRsListSelectedjPanelLayout = new javax.swing.GroupLayout(jobOperationNRsListSelectedjPanel);
        jobOperationNRsListSelectedjPanel.setLayout(jobOperationNRsListSelectedjPanelLayout);
        jobOperationNRsListSelectedjPanelLayout.setHorizontalGroup(
            jobOperationNRsListSelectedjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );
        jobOperationNRsListSelectedjPanelLayout.setVerticalGroup(
            jobOperationNRsListSelectedjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );

        jobOpeationNRsListSelectedjScrollPane.setViewportView(jobOperationNRsListSelectedjPanel);

        javax.swing.GroupLayout jobOperationNRListjPanelLayout = new javax.swing.GroupLayout(jobOperationNRListjPanel);
        jobOperationNRListjPanel.setLayout(jobOperationNRListjPanelLayout);
        jobOperationNRListjPanelLayout.setHorizontalGroup(
            jobOperationNRListjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jobOperationNRListjPanelLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jobOperationNRsjscrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jobOpeationNRsListSelectedjScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jobOperationNRListjPanelLayout.setVerticalGroup(
            jobOperationNRListjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jobOperationNRListjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jobOperationNRListjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jobOpeationNRsListSelectedjScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jobOperationNRsjscrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel2.setText("Idade");

        jTextField1.setText("26");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cpfJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pisjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(workPermitjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rgjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(nameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(169, 169, 169)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(militaryjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(asoDatejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(saveFormsjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addNewDependentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(adressComplementjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hieringDatejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cepjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                        .addComponent(salaryjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                        .addComponent(jobOperationNRListjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cityjTextField)
                        .addComponent(neighborhoodjTextField)
                        .addComponent(adressComplementjTextField)
                        .addComponent(streetjTextField)
                        .addComponent(jSeparator1)
                        .addComponent(militaryjTextField)
                        .addComponent(pisjTextField)
                        .addComponent(workPermitjTextField)
                        .addComponent(rgjTextField)
                        .addComponent(cpfjTextField)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(41, 41, 41)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addGap(127, 127, 127))
                        .addComponent(jSeparator2)
                        .addComponent(dependentsListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jobFunctionjListjScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(394, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameJLabel)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cpfJlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpfjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rgjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rgjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(workPermitjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workPermitjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pisjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pisjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(militaryjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(militaryjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(streetjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(adressComplementjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adressComplementjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(neighborhoodjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cepjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(24, 24, 24)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hieringDatejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(asoDatejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jobFunctionjListjScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salaryjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jobOperationNRListjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(3, 3, 3)
                .addComponent(addNewDependentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dependentsListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(saveFormsjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1078, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(2802, Short.MAX_VALUE)))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1853, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private final String[] JobLocalInputListOptionsPopulate = { "Obra", "Escritório" };

    private void JobLocalInputListOptionsPopulate() {

        jobLocalInputList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = JobLocalInputListOptionsPopulate;

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });

    }

    private void jobLocalInputListValueChanged(javax.swing.event.ListSelectionEvent evt) {// GEN-FIRST:event_jobLocalInputListValueChanged
        if (jobLocalInputList.getSelectedValue() == null ? JobLocalInputListOptionsPopulate[1] == null
                : jobLocalInputList.getSelectedValue().equals(JobLocalInputListOptionsPopulate[1])) {
            jobOperationNRListjPanel.setVisible(false);

        } else {
            jobOperationNRListjPanel.setVisible(true);

        }
        pack();
    }// GEN-LAST:event_jobLocalInputListValueChanged

    private void addNewDependentButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_addNewDependentButtonMouseClicked
        NewDependentPanel newDependentPanel = new NewDependentPanel(newDependentTextFieldList.size(),
                newDependentTextFieldList);

        newDependentTextFieldList.add(new NewDependentInput(
                newDependentPanel.nameTextField,
                newDependentPanel.dependencyTextField,
                newDependentPanel.ageTextField));

        dependentsListPanel.add(newDependentPanel);
        pack();
    }// GEN-LAST:event_addNewDependentButtonMouseClicked

    private void saveFormsjButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_saveFormsjButtonMouseClicked
        // TODO add your handling code here:
        System.out.println("");
        System.out.println("");
        System.out.println("");

        // JList components
        // System.out.println("jobFunctionjList: " +
        // jobFunctionjList.getSelectedValue());
        // System.out.println("jobLocalInputList: " +
        // jobLocalInputList.getSelectedValue());
        // System.out.println("jobOperationNRsList: " +
        // jobOperationNRsList.getSelectedValue());
        System.out.println("");
        System.out.println("Custom inputs:");

        System.out.println("newDependentTextFieldList:");
        for (NewDependentInput dependent : newDependentTextFieldList) {
            System.out.println(dependent.toString());
        }
        System.out.println("");
        System.out.println("");

        System.out.println("nrsChoosenDateList:");
        for (NRChosenInput nrsChoosen : nrsChoosenDateList) {
            System.out.println(nrsChoosen.toString());
        }
        System.out.println("");

        // // JTextField components
        // System.out.println("adressComplementjTextField: " +
        // adressComplementjTextField.getText());
        // System.out.println("cepjTextField: " + cepjTextField.getText());
        // System.out.println("cityjTextField: " + cityjTextField.getText());
        // System.out.println("cpfjTextField: " + cpfjTextField.getText());
        // System.out.println("militaryjTextField: " + militaryjTextField.getText());
        // System.out.println("namejTextField: " + namejTextField.getText());
        // System.out.println("neighborhoodjTextField: " +
        // neighborhoodjTextField.getText());
        // System.out.println("pisjTextField: " + pisjTextField.getText());
        // System.out.println("rgjTextField: " + rgjTextField.getText());
        // System.out.println("salaryjTextField: " + salaryjTextField.getText());
        // System.out.println("streetjTextField: " + streetjTextField.getText());
        // System.out.println("workPermitjTextField: " +
        // workPermitjTextField.getText());
        // JDateChooser components
        // System.out.println("asoDatejDateChooser: " +
        // (asoDatejDateChooser.getDate()));
        // System.out.println("hieringDatejDateChooser: " +
        // (hieringDatejDateChooser.getDate()));
    }// GEN-LAST:event_saveFormsjButtonMouseClicked

    private void jobFunctionjListMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jobFunctionjListMouseClicked
        JList<String> source = (JList<String>) evt.getSource();
        String selectedValue = source.getSelectedValue();
        salaryjTextField.setText(Double.toString(jobList.salaryByTitle(selectedValue)));
    }// GEN-LAST:event_jobFunctionjListMouseClicked

    private void jobOperationNRsListMouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jobOperationNRsListMouseReleased
        // TODO add your handling code here:
        JList<String> source = (JList<String>) evt.getSource();
        String nrSelected = source.getSelectedValue().split("%")[0].trim();
        System.out.println(nrSelected);

        for (NRChosenInput nrsChoosen : nrsChoosenDateList) {
            if (nrsChoosen.nr == null ? nrSelected == null : nrsChoosen.nr.equals(nrSelected)) {
                return;
            }
        }
        NRsChosenPanel nRsChoosenPanel = new NRsChosenPanel(nrSelected, nrsChoosenDateList);

        nrsChoosenDateList.add(new NRChosenInput(nRsChoosenPanel.nrExamDateChooser, nrSelected));

        jobOperationNRListjPanel.add(nRsChoosenPanel);

        jobOperationNRsListSelectedjPanel.add(nRsChoosenPanel);

        pack();
    }// GEN-LAST:event_jobOperationNRsListMouseReleased
     // GEN-LAST:event_dependentsCheckBoxActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUserFormsFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUserFormsFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUserFormsFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUserFormsFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUserFormsFrame().setVisible(true);
            }
        });
    }

    // Variables not netbeans;
    private final ArrayList<NewDependentInput> newDependentTextFieldList;
    private final ArrayList<NRChosenInput> nrsChoosenDateList = new ArrayList<NRChosenInput>();
    private final JobsAvailable jobList = new JobsAvailable();

    // End ofVariables not netbeans;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewDependentButton;
    private javax.swing.JLabel adressComplementjLabel;
    private javax.swing.JTextField adressComplementjTextField;
    private com.toedter.calendar.JDateChooser asoDatejDateChooser;
    private javax.swing.JTextField cepjTextField;
    private javax.swing.JTextField cityjTextField;
    private javax.swing.JLabel cpfJlabel;
    private javax.swing.JTextField cpfjTextField;
    private javax.swing.JPanel dependentsListPanel;
    private javax.swing.JScrollPane dependentsListScrollPane;
    private com.toedter.calendar.JDateChooser hieringDatejDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JList<String> jobFunctionjList;
    private javax.swing.JScrollPane jobFunctionjListjScrollPane;
    private javax.swing.JList<String> jobLocalInputList;
    private javax.swing.JScrollPane jobOpeationNRsListSelectedjScrollPane;
    private javax.swing.JPanel jobOperationNRListjPanel;
    private javax.swing.JList<String> jobOperationNRsList;
    private javax.swing.JPanel jobOperationNRsListSelectedjPanel;
    private javax.swing.JScrollPane jobOperationNRsjscrollPane;
    private javax.swing.JLabel militaryjLabel;
    private javax.swing.JTextField militaryjTextField;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JTextField neighborhoodjTextField;
    private javax.swing.JLabel pisjLabel;
    private javax.swing.JTextField pisjTextField;
    private javax.swing.JLabel rgjLabel;
    private javax.swing.JTextField rgjTextField;
    private javax.swing.JTextField salaryjTextField;
    private javax.swing.JButton saveFormsjButton;
    private javax.swing.JTextField streetjTextField;
    private javax.swing.JLabel workPermitjLabel;
    private javax.swing.JTextField workPermitjTextField;
    // End of variables declaration//GEN-END:variables
}