/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modena.ui.appFrames.forms.newUserForms;

import com.toedter.calendar.JDateChooser;

import modena.ui.appFrames.forms.newUserForms.NewUserFormsFrameBusiness.NewUserFormsFrameBusinessProps;
import modena.ui.appFrames.forms.newUserForms.NewUserFormsFrameBusiness.UserDependentProps;

import java.util.ArrayList;
import java.util.Date;

import javax.swing.BoxLayout;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import resources.dataArray.JobsAvailable;
import resources.dataArray.NRList;

/**
 *
 * @author felip
 */
public class NewUserFormsFrame extends javax.swing.JFrame {

        /**
         * Creates new form newUserForms
         */
        public NewUserFormsFrame() {
                initComponents();
                initCustomComponents();
                newDependentTextFieldList = new ArrayList<>();
                JobLocalInputListOptionsPopulate();
        }

        public class NewDependentInput {

                JTextField name;
                JTextField dependency;
                JTextField age;

                NewDependentInput(JTextField name, JTextField dependency, JTextField age) {
                        this.name = name;
                        this.dependency = dependency;
                        this.age = age;
                }

                @Override
                public String toString() {
                        return "Name: " + name.getText() + ", Dependency: " + dependency.getText() + ", Age: "
                                        + age.getText();
                }

        }

        public class NRChosenInput {

                JDateChooser date;
                String nr;

                NRChosenInput(JDateChooser date, String nr) {
                        this.date = date;
                        this.nr = nr;
                }

                @Override
                public String toString() {
                        return "Nr: " + nr + " / " + "Date: " + date.getDate();
                }

        }

        private void initCustomComponents() {
                dependentsListPanel.setLayout(new BoxLayout(dependentsListPanel, BoxLayout.Y_AXIS));
                jobOperationNRsListSelectedJPanel
                                .setLayout(new BoxLayout(jobOperationNRsListSelectedJPanel, BoxLayout.Y_AXIS));

                jobOperationNRListPopulate();
                jobFunctionJListPopulate();
        }

        private void jobOperationNRListPopulate() {
                jobOperationNRsList.setModel(new javax.swing.AbstractListModel<String>() {
                        NRList nrList = new NRList();
                        String[] strings = nrList.NRListConcat();

                        public int getSize() {
                                return strings.length;
                        }

                        public String getElementAt(int i) {
                                return strings[i];
                        }
                });
                jobOperationNRsJScrollPane.setViewportView(jobOperationNRsList);

        }

        private void jobFunctionJListPopulate() {
                jobFunctionJList.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = jobList.listOfJobsTitle();

                        public int getSize() {
                                return strings.length;
                        }

                        public String getElementAt(int i) {
                                return strings[i];
                        }
                });
                jobFunctionJListJScrollPane.setViewportView(jobFunctionJList);

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                JPanel1 = new javax.swing.JPanel();
                JLabel1 = new javax.swing.JLabel();
                nameJLabel = new javax.swing.JLabel();
                cpfJLabel = new javax.swing.JLabel();
                rgJLabel = new javax.swing.JLabel();
                workPermitJLabel = new javax.swing.JLabel();
                pisJLabel = new javax.swing.JLabel();
                militaryJLabel = new javax.swing.JLabel();
                nameJTextField = new javax.swing.JTextField();
                rgJTextField = new javax.swing.JTextField();
                cpfJTextField = new javax.swing.JTextField();
                workPermitJTextField = new javax.swing.JTextField();
                militaryJTextField = new javax.swing.JTextField();
                pisJTextField = new javax.swing.JTextField();
                JLabel9 = new javax.swing.JLabel();
                streetJTextField = new javax.swing.JTextField();
                JLabel8 = new javax.swing.JLabel();
                addressComplementJLabel = new javax.swing.JLabel();
                addressComplementJTextField = new javax.swing.JTextField();
                JLabel11 = new javax.swing.JLabel();
                neighborhoodJTextField = new javax.swing.JTextField();
                JLabel12 = new javax.swing.JLabel();
                cityJTextField = new javax.swing.JTextField();
                JLabel13 = new javax.swing.JLabel();
                cepJTextField = new javax.swing.JTextField();
                JLabel14 = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();
                jSeparator2 = new javax.swing.JSeparator();
                JLabel3 = new javax.swing.JLabel();
                JLabel15 = new javax.swing.JLabel();
                heiringDateDateChooser = new com.toedter.calendar.JDateChooser();
                JLabel16 = new javax.swing.JLabel();
                asoDateJDateChooser = new com.toedter.calendar.JDateChooser();
                jobFunctionJListJScrollPane = new javax.swing.JScrollPane();
                jobFunctionJList = new javax.swing.JList<>();
                JLabel17 = new javax.swing.JLabel();
                JLabel18 = new javax.swing.JLabel();
                salaryJTextField = new javax.swing.JTextField();
                JLabel19 = new javax.swing.JLabel();
                jScrollPane3 = new javax.swing.JScrollPane();
                jobLocalInputList = new javax.swing.JList<>();
                addNewDependentButton = new javax.swing.JButton();
                dependentsListScrollPane = new javax.swing.JScrollPane();
                dependentsListPanel = new javax.swing.JPanel();
                saveFormsJButton = new javax.swing.JButton();
                jobOperationNRListJPanel = new javax.swing.JPanel();
                jobOperationNRsJScrollPane = new javax.swing.JScrollPane();
                jobOperationNRsList = new javax.swing.JList<>();
                jobOperationNRsListSelectedJScrollPane = new javax.swing.JScrollPane();
                jobOperationNRsListSelectedJPanel = new javax.swing.JPanel();
                jSeparator3 = new javax.swing.JSeparator();
                JLabel2 = new javax.swing.JLabel();
                ageJTextField = new javax.swing.JTextField();
                JLabel4 = new javax.swing.JLabel();
                emailJTextField = new javax.swing.JTextField();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                JLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                JLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                JLabel1.setText("Adicionar novo colaborador");

                nameJLabel.setLabelFor(nameJTextField);
                nameJLabel.setText("Nome do colaborador");

                cpfJLabel.setLabelFor(cpfJTextField);
                cpfJLabel.setText("CPF");

                rgJLabel.setLabelFor(rgJLabel);
                rgJLabel.setText("RG");

                workPermitJLabel.setLabelFor(workPermitJTextField);
                workPermitJLabel.setText("Carteira de trabalho");

                pisJLabel.setText("PIS");

                militaryJLabel.setText("Reservista");

                nameJTextField.setText("user1");

                rgJTextField.setText("502332578");

                cpfJTextField.setText("46260974809");

                workPermitJTextField.setText("23214343 valor tal21312");

                militaryJTextField.setText("2132423213-213");

                pisJTextField.setText("1234dds123");

                JLabel9.setText("Rua");

                streetJTextField.setText("rua tal");

                JLabel8.setText("Possui dependentes?");

                addressComplementJLabel.setText("Complemento");

                addressComplementJTextField.setText("complemento tal");

                JLabel11.setText("Bairro");

                neighborhoodJTextField.setText("bairro tal");

                JLabel12.setText("Cidade");

                cityJTextField.setText("cidade tal");

                JLabel13.setText("CEP");

                cepJTextField.setText("0642900");

                JLabel14.setText("Data de contratação");

                JLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                JLabel3.setText("Endereço");

                JLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                JLabel15.setText("Registro de contratação");

                JLabel16.setText("Data  de ASO (exame médico)");

                jobFunctionJList.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = { "lista de funções de JobsAvailable.java" };

                        public int getSize() {
                                return strings.length;
                        }

                        public String getElementAt(int i) {
                                return strings[i];
                        }
                });
                jobFunctionJList.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jobFunctionJListMouseClicked(evt);
                        }
                });
                jobFunctionJListJScrollPane.setViewportView(jobFunctionJList);

                JLabel17.setText("Função");

                JLabel18.setText("Salário ( usar ponto (.) para centavos)");

                salaryJTextField.setText("1500");

                JLabel19.setText("Local de operação");

                jobLocalInputList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
                        public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                                jobLocalInputListValueChanged(evt);
                        }
                });
                jScrollPane3.setViewportView(jobLocalInputList);

                addNewDependentButton.setText("Adicionar dependente");
                addNewDependentButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                addNewDependentButtonMouseClicked(evt);
                        }
                });

                dependentsListPanel.setFocusCycleRoot(true);

                javax.swing.GroupLayout dependentsListPanelLayout = new javax.swing.GroupLayout(dependentsListPanel);
                dependentsListPanel.setLayout(dependentsListPanelLayout);
                dependentsListPanelLayout.setHorizontalGroup(
                                dependentsListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 878, Short.MAX_VALUE));
                dependentsListPanelLayout.setVerticalGroup(
                                dependentsListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 175, Short.MAX_VALUE));

                dependentsListScrollPane.setViewportView(dependentsListPanel);

                saveFormsJButton.setText("Salvar");
                saveFormsJButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                saveFormsJButtonMouseClicked(evt);
                        }
                });

                jobOperationNRsList.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = { "lista de nrs de NRList.java" };

                        public int getSize() {
                                return strings.length;
                        }

                        public String getElementAt(int i) {
                                return strings[i];
                        }
                });
                jobOperationNRsList.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jobOperationNRsListMouseReleased(evt);
                        }
                });
                jobOperationNRsJScrollPane.setViewportView(jobOperationNRsList);

                javax.swing.GroupLayout jobOperationNRsListSelectedJPanelLayout = new javax.swing.GroupLayout(
                                jobOperationNRsListSelectedJPanel);
                jobOperationNRsListSelectedJPanel.setLayout(jobOperationNRsListSelectedJPanelLayout);
                jobOperationNRsListSelectedJPanelLayout.setHorizontalGroup(
                                jobOperationNRsListSelectedJPanelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 655, Short.MAX_VALUE));
                jobOperationNRsListSelectedJPanelLayout.setVerticalGroup(
                                jobOperationNRsListSelectedJPanelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 179, Short.MAX_VALUE));

                jobOperationNRsListSelectedJScrollPane.setViewportView(jobOperationNRsListSelectedJPanel);

                javax.swing.GroupLayout jobOperationNRListJPanelLayout = new javax.swing.GroupLayout(
                                jobOperationNRListJPanel);
                jobOperationNRListJPanel.setLayout(jobOperationNRListJPanelLayout);
                jobOperationNRListJPanelLayout.setHorizontalGroup(
                                jobOperationNRListJPanelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jobOperationNRListJPanelLayout.createSequentialGroup()
                                                                                .addContainerGap(7, Short.MAX_VALUE)
                                                                                .addComponent(jobOperationNRsJScrollPane,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                287,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jobOperationNRsListSelectedJScrollPane,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                398,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addContainerGap()));
                jobOperationNRListJPanelLayout.setVerticalGroup(
                                jobOperationNRListJPanelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jobOperationNRListJPanelLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jobOperationNRListJPanelLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                false)
                                                                                .addComponent(jobOperationNRsListSelectedJScrollPane,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                0, Short.MAX_VALUE)
                                                                                .addComponent(jobOperationNRsJScrollPane,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                118,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(12, Short.MAX_VALUE)));

                JLabel2.setText("Idade");

                ageJTextField.setText("26");

                JLabel4.setText("email (não obrigatório)");

                emailJTextField.setText("email.com.br");

                javax.swing.GroupLayout JPanel1Layout = new javax.swing.GroupLayout(JPanel1);
                JPanel1.setLayout(JPanel1Layout);
                JPanel1Layout.setHorizontalGroup(
                                JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(JPanel1Layout.createSequentialGroup()
                                                                .addGap(19, 19, 19)
                                                                .addGroup(JPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(cpfJLabel,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                196,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(pisJLabel,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                196,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(workPermitJLabel,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                196,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(rgJLabel,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                196,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(militaryJLabel,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                196,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(JLabel14,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                196,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(JLabel15,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                159,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(asoDateJDateChooser,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(saveFormsJButton,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                166,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(JLabel8,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                196,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(addNewDependentButton,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                165,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(JLabel18,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                195,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jSeparator3,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(JLabel9,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                196,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(addressComplementJLabel,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                196,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(JLabel11,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                196,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(JLabel12,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                196,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(JLabel13,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                196,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(JLabel3,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                107,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(JLabel17,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                43,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(JLabel16,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                196,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(heiringDateDateChooser,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(cepJTextField,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                704, Short.MAX_VALUE)
                                                                                .addComponent(salaryJTextField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                121,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jScrollPane3,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                0, Short.MAX_VALUE)
                                                                                .addComponent(JLabel19,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                704, Short.MAX_VALUE)
                                                                                .addComponent(jobOperationNRListJPanel,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(cityJTextField)
                                                                                .addComponent(neighborhoodJTextField)
                                                                                .addComponent(addressComplementJTextField)
                                                                                .addComponent(streetJTextField)
                                                                                .addComponent(jSeparator1)
                                                                                .addComponent(militaryJTextField)
                                                                                .addComponent(pisJTextField)
                                                                                .addComponent(workPermitJTextField)
                                                                                .addComponent(rgJTextField)
                                                                                .addComponent(cpfJTextField)
                                                                                .addGroup(JPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(nameJTextField,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                324,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(41, 41, 41)
                                                                                                .addComponent(ageJTextField,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                212,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addGap(127, 127, 127))
                                                                                .addComponent(jSeparator2)
                                                                                .addComponent(dependentsListScrollPane,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                644,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jobFunctionJListJScrollPane,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                347,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(emailJTextField)
                                                                                .addComponent(JLabel4,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(JPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(nameJLabel,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                196,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(169, 169, 169)
                                                                                                .addComponent(JLabel2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                50,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(JLabel1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap(96, Short.MAX_VALUE)));
                JPanel1Layout.setVerticalGroup(
                                JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(JPanel1Layout.createSequentialGroup()
                                                                .addGap(28, 28, 28)
                                                                .addComponent(JLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                44,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(JPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(nameJLabel)
                                                                                .addComponent(JLabel2))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(JPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(nameJTextField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(ageJTextField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(JLabel4)
                                                                .addGap(4, 4, 4)
                                                                .addComponent(emailJTextField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(15, 15, 15)
                                                                .addComponent(cpfJLabel)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cpfJTextField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(rgJLabel)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(rgJTextField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(workPermitJLabel)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(workPermitJTextField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                22,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(pisJLabel)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(pisJTextField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(12, 12, 12)
                                                                .addComponent(militaryJLabel)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(militaryJTextField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jSeparator1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                10,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(JLabel3)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(JLabel9)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(streetJTextField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(addressComplementJLabel)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(addressComplementJTextField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(JLabel11)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(neighborhoodJTextField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(JLabel12)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cityJTextField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(JLabel13)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cepJTextField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jSeparator2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                10,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(JLabel15)
                                                                .addGap(24, 24, 24)
                                                                .addComponent(JLabel14)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(heiringDateDateChooser,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(JLabel16)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(asoDateJDateChooser,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(JLabel17)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jobFunctionJListJScrollPane,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                91,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(JLabel18,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                16,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(salaryJTextField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(24, 24, 24)
                                                                .addComponent(JLabel19)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jScrollPane3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                44,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jobOperationNRListJPanel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(33, 33, 33)
                                                                .addComponent(jSeparator3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                13,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(JLabel8)
                                                                .addGap(3, 3, 3)
                                                                .addComponent(addNewDependentButton)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(dependentsListScrollPane,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                169,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(47, 47, 47)
                                                                .addComponent(saveFormsJButton,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                57,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(1126, Short.MAX_VALUE)));

                jScrollPane1.setViewportView(JPanel1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 767,
                                                                Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 1853,
                                                                Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private final String[] JobLocalInputListOptionsPopulate = { "Obra", "Escritório" };

        private void JobLocalInputListOptionsPopulate() {

                jobLocalInputList.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = JobLocalInputListOptionsPopulate;

                        public int getSize() {
                                return strings.length;
                        }

                        public String getElementAt(int i) {
                                return strings[i];
                        }
                });

        }

        private void jobLocalInputListValueChanged(javax.swing.event.ListSelectionEvent evt) {// GEN-FIRST:event_jobLocalInputListValueChanged
                if (jobLocalInputList.getSelectedValue() == null ? JobLocalInputListOptionsPopulate[1] == null
                                : jobLocalInputList.getSelectedValue().equals(JobLocalInputListOptionsPopulate[1])) {
                        jobOperationNRListJPanel.setVisible(false);

                } else {
                        jobOperationNRListJPanel.setVisible(true);

                }
                pack();
        }// GEN-LAST:event_jobLocalInputListValueChanged

        private void addNewDependentButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_addNewDependentButtonMouseClicked
                NewDependentPanel newDependentPanel = new NewDependentPanel(newDependentTextFieldList.size(),
                                newDependentTextFieldList);

                newDependentTextFieldList.add(new NewDependentInput(
                                newDependentPanel.nameTextField,
                                newDependentPanel.dependencyTextField,
                                newDependentPanel.ageTextField));

                dependentsListPanel.add(newDependentPanel);
                pack();
        }// GEN-LAST:event_addNewDependentButtonMouseClicked

        private void saveFormsJButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_saveFormsJButtonMouseClicked
                ArrayList<String> erros = new ArrayList<String>();

                if (nameJTextField.getText().length() < 1) {
                        erros.add("Campo nome vazio");
                }

                if (ageJTextField.getText().length() < 1) {
                        erros.add("Campo idade vazio");
                }

                if (cpfJTextField.getText().length() < 1) {
                        erros.add("Campo cpf vazio");
                }

                if (emailJTextField.getText().length() < 1) {
                        erros.add("Campo email vazio");
                }

                if (rgJTextField.getText().length() < 1) {
                        erros.add("Campo rg vazio");
                }

                if (workPermitJTextField.getText().length() < 1) {
                        erros.add("Campo carteira de trabalho vazio");
                }

                if (pisJTextField.getText().length() < 1) {
                        erros.add("Campo pis vazio");
                }

                if (militaryJTextField.getText().length() < 1) {
                        erros.add("Campo reservista vazio");
                }

                if (streetJTextField.getText().length() < 1) {
                        erros.add("Campo rua vazio");
                }

                if (addressComplementJTextField.getText().length() < 1) {
                        erros.add("Campo complemento vazio");
                }

                if (neighborhoodJTextField.getText().length() < 1) {
                        erros.add("Campo bairro vazio");
                }

                if (cityJTextField.getText().length() < 1) {
                        erros.add("Campo cidade vazio");
                }

                if (cepJTextField.getText().length() < 1) {
                        erros.add("Campo CEP vazio");
                }

                if (heiringDateDateChooser.getDate() == null) {
                        erros.add("Campo data de contratação vazio");
                }

                if (asoDateJDateChooser.getDate() == null) {
                        erros.add("Campo data de ASO vazio");
                }

                if (jobFunctionJList.getSelectedValue() == null) {
                        erros.add("Selecione uma função");
                }

                if (salaryJTextField.getText().length() < 1) {
                        erros.add("Campo salário vazio");
                }

                if (jobLocalInputList.getSelectedValue() == null) {
                        erros.add("Selecione um local de trabalho");
                }

                if (erros.size() < 0) {
                        String errosString = "";
                        for (String erro : erros) {
                                errosString += "> " + erro + "\n";
                        }
                        JOptionPane.showMessageDialog(null, errosString);
                } else

                        sendDataToBusiness();

        }// GEN-LAST:event_saveFormsJButtonMouseClicked

        private void sendDataToBusiness() {
                ArrayList<String> address = new ArrayList<String>();
                address.add(cityJTextField.getText());
                address.add(streetJTextField.getText());
                address.add(neighborhoodJTextField.getText());
                address.add(addressComplementJTextField.getText());

                heiringDateDateChooser.setDate(new Date());

                asoDateJDateChooser.setDate(new Date());
                jobFunctionJList.setSelectedIndex(0);
                jobLocalInputList.setSelectedIndex(1);
                NewUserFormsFrameBusiness newUserFormsFrameBusiness = new NewUserFormsFrameBusiness();
                NewUserFormsFrameBusiness.NewUserFormsFrameBusinessProps newUserFormsFrameBusinessProps = newUserFormsFrameBusiness.new NewUserFormsFrameBusinessProps(
                                nameJTextField.getText(),
                                Integer.parseInt(ageJTextField.getText()),
                                emailJTextField.getText(),
                                cpfJTextField.getText(),
                                rgJTextField.getText(),
                                address,
                                Double.parseDouble(salaryJTextField.getText()),
                                pisJTextField.getText(),
                                workPermitJTextField.getText(),
                                militaryJTextField.getText(),
                                heiringDateDateChooser.getDate(),
                                jobLocalInputList.getSelectedValue(),
                                asoDateJDateChooser.getDate(),
                                jobFunctionJList.getSelectedValue(), jobLocalInputList.getSelectedValue());

                int createNewUserResponse = newUserFormsFrameBusiness.createNewUser(newUserFormsFrameBusinessProps);

                if (newDependentTextFieldList.size() > 0) {

                        ArrayList<UserDependentProps> userDependentProps = new ArrayList<UserDependentProps>();
                        for (NewDependentInput newDependentTextFieldList : newDependentTextFieldList) {
                                userDependentProps.add(newUserFormsFrameBusiness.new UserDependentProps(
                                                newDependentTextFieldList.name.getText(),
                                                Integer.parseInt(newDependentTextFieldList.age.getText()),
                                                newDependentTextFieldList.dependency.getText()
                                                ));


                        }

                        newUserFormsFrameBusiness.createUserDependents(createNewUserResponse, userDependentProps);
                }

        }

        private void jobFunctionJListMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jobFunctionJListMouseClicked
                JList<String> source = (JList<String>) evt.getSource();
                String selectedValue = source.getSelectedValue();
                salaryJTextField.setText(Double.toString(jobList.salaryByTitle(selectedValue)));
        }// GEN-LAST:event_jobFunctionJListMouseClicked

        private void jobOperationNRsListMouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jobOperationNRsListMouseReleased
                // TODO add your handling code here:
                JList<String> source = (JList<String>) evt.getSource();
                String nrSelected = source.getSelectedValue().split("%")[0].trim();
                System.out.println(nrSelected);

                for (NRChosenInput nrsChosen : nrsChosenDateList) {
                        if (nrsChosen.nr == null ? nrSelected == null : nrsChosen.nr.equals(nrSelected)) {
                                return;
                        }
                }
                NRsChosenPanel nRsChosenPanel = new NRsChosenPanel(nrSelected, nrsChosenDateList);

                nrsChosenDateList.add(new NRChosenInput(nRsChosenPanel.nrExamDateChooser, nrSelected));

                jobOperationNRListJPanel.add(nRsChosenPanel);

                jobOperationNRsListSelectedJPanel.add(nRsChosenPanel);

                pack();
        }// GEN-LAST:event_jobOperationNRsListMouseReleased
         // GEN-LAST:event_dependentsCheckBoxActionPerformed

        private void JTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_JTextField1ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_JTextField1ActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(NewUserFormsFrame.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null,
                                        ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(NewUserFormsFrame.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null,
                                        ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(NewUserFormsFrame.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null,
                                        ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(NewUserFormsFrame.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null,
                                        ex);
                }
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new NewUserFormsFrame().setVisible(true);
                        }
                });
        }

        // Variables not netbeans;
        private final ArrayList<NewDependentInput> newDependentTextFieldList;
        private final ArrayList<NRChosenInput> nrsChosenDateList = new ArrayList<NRChosenInput>();
        private final JobsAvailable jobList = new JobsAvailable();

        // End ofVariables not netbeans;
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton addNewDependentButton;
        private javax.swing.JLabel addressComplementJLabel;
        private javax.swing.JTextField addressComplementJTextField;
        private javax.swing.JTextField ageJTextField;
        private com.toedter.calendar.JDateChooser asoDateJDateChooser;
        private javax.swing.JTextField cepJTextField;
        private javax.swing.JTextField cityJTextField;
        private javax.swing.JLabel cpfJLabel;
        private javax.swing.JTextField cpfJTextField;
        private javax.swing.JPanel dependentsListPanel;
        private javax.swing.JScrollPane dependentsListScrollPane;
        private javax.swing.JTextField emailJTextField;
        private com.toedter.calendar.JDateChooser heiringDateDateChooser;
        private javax.swing.JLabel JLabel1;
        private javax.swing.JLabel JLabel11;
        private javax.swing.JLabel JLabel12;
        private javax.swing.JLabel JLabel13;
        private javax.swing.JLabel JLabel14;
        private javax.swing.JLabel JLabel15;
        private javax.swing.JLabel JLabel16;
        private javax.swing.JLabel JLabel17;
        private javax.swing.JLabel JLabel18;
        private javax.swing.JLabel JLabel19;
        private javax.swing.JLabel JLabel2;
        private javax.swing.JLabel JLabel3;
        private javax.swing.JLabel JLabel4;
        private javax.swing.JLabel JLabel8;
        private javax.swing.JLabel JLabel9;
        private javax.swing.JPanel JPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JSeparator jSeparator2;
        private javax.swing.JSeparator jSeparator3;
        private javax.swing.JList<String> jobFunctionJList;
        private javax.swing.JScrollPane jobFunctionJListJScrollPane;
        private javax.swing.JList<String> jobLocalInputList;
        private javax.swing.JScrollPane jobOperationNRsListSelectedJScrollPane;
        private javax.swing.JPanel jobOperationNRListJPanel;
        private javax.swing.JList<String> jobOperationNRsList;
        private javax.swing.JPanel jobOperationNRsListSelectedJPanel;
        private javax.swing.JScrollPane jobOperationNRsJScrollPane;
        private javax.swing.JLabel militaryJLabel;
        private javax.swing.JTextField militaryJTextField;
        private javax.swing.JLabel nameJLabel;
        private javax.swing.JTextField nameJTextField;
        private javax.swing.JTextField neighborhoodJTextField;
        private javax.swing.JLabel pisJLabel;
        private javax.swing.JTextField pisJTextField;
        private javax.swing.JLabel rgJLabel;
        private javax.swing.JTextField rgJTextField;
        private javax.swing.JTextField salaryJTextField;
        private javax.swing.JButton saveFormsJButton;
        private javax.swing.JTextField streetJTextField;
        private javax.swing.JLabel workPermitJLabel;
        private javax.swing.JTextField workPermitJTextField;
        // End of variables declaration//GEN-END:variables
}