/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package modena.ui.appFrames.forms.newUserForms;

import java.util.ArrayList;

/**
 *
 * @author felip
 */
public class NRsChosenPanel extends javax.swing.JPanel {

    ArrayList<NewUserFormsFrame.NRChosenInput> nrList = new ArrayList< NewUserFormsFrame.NRChosenInput>();
    int position;

    /**
     * Creates new form newDependentPanel
     *
     * @param order
     */
    public NRsChosenPanel(String nr, ArrayList<NewUserFormsFrame.NRChosenInput> list) {
        initComponents();
        this.nrList = list;
        nrTitlejLabel.setText(nr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nrTitlejLabel = new javax.swing.JLabel();
        deleteJButton = new javax.swing.JButton();
        nrExamDateChooser = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(204, 204, 204));

        nrTitlejLabel.setText("Param");

        deleteJButton.setBackground(new java.awt.Color(255, 102, 102));
        deleteJButton.setText("Apagar");
        deleteJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteJButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nrTitlejLabel)
                .addGap(18, 18, 18)
                .addComponent(nrExamDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteJButton)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nrExamDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(deleteJButton)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nrTitlejLabel)))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteJButtonMouseClicked
        if (!nrList.isEmpty()) {
            nrList.remove(position);
            setVisible(false);
        }
    }//GEN-LAST:event_deleteJButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteJButton;
    public com.toedter.calendar.JDateChooser nrExamDateChooser;
    private javax.swing.JLabel nrTitlejLabel;
    // End of variables declaration//GEN-END:variables
}
